### ISSUE TITLE
Util class not defined when using components that need it

### ISSUE THREAD

**Issue by YannickMol** [peiche/gatsby-starter-codyhouse#1]
Hey man, love what you have done with this. Was looking for this and tried to get it working myself, but didn't succeed. With your help I am now able to create Gatsby websites with CH components much quicker, thanks! 

One thing which I can't get to work is the Page Transition Component with the Page Transition Plugin - do you have any idea how to get this to work?

Thanks again and keep up the great work!

**Comment by peiche** [comment]
Gatsby has its own [component for internal navigation](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/). While this doesn't enable the use of CodyHouse's page transitions plugin, there does exist a [Gatsby plugin](https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-page-transitions-with-plugin-transition-link/) to implement something similar. I recommend giving that a shot.

**Comment by YannickMol** [comment]
Thanks @peiche for the reply! I am aware of Gatsby's internal navigation component. I was just curious how to implement components where two scripts are required. Another example would be the Chart Plugin. I'll give it another go, but please let me know if you have any thoughts on how to get this working :)

**Comment by YannickMol** [comment]
Hi @peiche, I am still facing this issue with any js file I include in the component. Are you facing a similar issue?

**Comment by peiche** [comment]
Hi @YannickMol, I did run into this issue while updating another site that used this starter. The issue was that by loading `util.js` in the Layout component, the rendering (and subsequent programmatic loading of js) would actually finish _after_ all other components are done loaded. The solution to this was to move loading `util.js` in the header, which finishes rendering (and loading js) before moving on to other components in the body.

I've just made these changes to the starter: I removed the `util.js` loader from the Layout component, and moved it inside the Header component. I think following this pattern will solve your "missing util.js" errors. (It did mine with loading a carousel component js.)

Alternatively, you could just load all the CodyHouse scripts all after loading util.js, one after another in a single component. (I wouldn't recommend that, since you might not need it on a given page. Then again, I don't know your use case.)

**Comment by YannickMol** [comment]
Thanks @peiche , this fixes the issue for me!
